=== alfg/opendrinks/scripts/recipe_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/alfg/opendrinks/master/scripts/recipe_schema.json",
    "title": "Recipe",
    "description": "A recipe of a drink or cocktail for opendrinks",
    "type": "object",
    "properties": {
      "name": {
        "description": "The name of the drink",
        "type": "string"
      },
      "description": {
        "description": "A short text describing the drink",
        "type": "string"
      },
      "github": {
        "description": "Github-Username of the contributor",
        "type": "string"
      },
      "ingredients": {
        "description": "The ingredients used for the drink",
        "type": "array",
        "minItems": 1,
        "items": {
          "description": "An ingredient",
          "type" :"object",
          "properties": {
            "quantity": {
              "description": "How much of the ingredient is needed",
              "type": "string"
            },
            "measure": {
              "description": "The unit of measurement of what is needed",
              "type": "string"
            },
            "ingredient": {
              "description": "The name of the ingredient",
              "type": "string"
            }
          },
          "required": [
            "quantity",
            "ingredient"
          ] 
        }
      },
      "directions": {
        "description": "How the drink is made",
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "string"
        }
      },
      "image": {
        "description": "An image of the drink",
        "type": "string"
      },
      "source": {
        "description": "Source of the recipe",
        "type": "string"
      },
      "keywords": {
        "description": "Keywords that describe the drink",
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "string"
        }
      }
    },
    "required": [
      "name",
      "description",
      "ingredients",
      "directions",
      "image",
      "keywords"
    ]
  }

=== alfg/opendrinks/src/recipes/mocha.json
{
    "name": "Mocha",
    "description": "A warm and rich chocolaty coffee. Simple and easy to make.",
    "github": "caliLai",
    "ingredients": [
        {
            "quantity": "1",
            "measure": "shot",
            "ingredient": "espresso or strong coffee"
        },
        {
            "quantity": "1",
            "measure": "cup",
            "ingredient": "milk"
        },
        {
            "quantity": "2",
            "measure": "tablespoons",
            "ingredient": "cocoa powder"
        },
        {
            "quantity": "",
            "measure": "",
            "ingredient": "sugar (to taste)"
        }
    ],
    "directions": [
        "Warm up milk in a small pot. Shut off heat just before it boils.",
        "Stir in the cocoa powder and sugar, ensuring that there are no clumps and the sugar is dissolved.",
        "Pour your espresso and milk into your cup of choice.",
        "Optional: garnish with whipped cream and extra cocoa powder.",
        "Enjoy!"
    ],
    "image": "mocha.jpg",
    "keywords": [
        "espresso",
        "chocolate",
        "hot"
    ]
}

=== alfg/opendrinks/src/recipes/mariposa-drink.json
{
    "name": "Mariposa",
    "description": "A rum drink contributed by The Bartending School",
    "github": "nathaniellers",
    "ingredients": [
        {
            "quantity": "1",
            "measure": "oz",
            "ingredient": "light rum"
        },
        {
            "quantity": "1/2",
            "measure": "oz",
            "ingredient": "brandy"
        },
        {
            "quantity": "1",
            "measure": "tablespoon",
            "ingredient": "lemon juice"
        },
        {
            "quantity": "1",
            "measure": "tablespoon",
            "ingredient": "orange"
        }
    ],
    "directions": [
        "Shake all ingredients together with ice",
        "strain into a cocktail glass"
    ],
    "image": "mariposa,jpg",
    "keywords": [
        "fancy",
        "alcohol",
        "cocktail",
        "mixed drink"
    ]
}

=== alfg/opendrinks/src/recipes/jammy-dodger-shot.json
{
    "name": "Jammy Dodger Shot",
    "description": "The Jammy Dodger is the best-tasting shot that will ever grace your mouth. You won't be grimacing when you knock this one back!",
    "github": "CalumChamberlain",
    "ingredients": [
        {
            "quantity": "3 quarters",
            "measure": "shot",
            "ingredient": "Chambord (blackberry liquor)"
        },
        {
            "quantity": "1 quarter",
            "measure": "shot",
            "ingredient": "double cream"
        },
        {
            "quantity": "half",
            "measure": "tsp",
            "ingredient": "sugar"
        }
    ],
    "directions": [
        "Fill the shot glass 3 quarters full with Chambord",
        "Top up the shot with cream",
        "Sprinkle a little sugar on top, knock it back and enjoy!"
    ],
    "image": "jammy-dodger-shot.jpg",
    "keywords": [
        "blackberry liqueur",
        "sugar",
        "shot",
        "blackberry"
    ]
}

=== alfg/opendrinks/src/recipes/peach-bellini.json
{
    "name": "Peach Bellini",
    "description": "Frozen, refreshing peach bellini made popular by the Joey restaurants! (Not the same but we try to get there)",
    "github": "brucremo",
    "ingredients": [
        {
            "quantity": "4",
            "measure": "cup",
            "ingredient": "Frozen & Sliced Peaches"
        },
        {
            "quantity": "2",
            "measure": "oz",
            "ingredient": "Peach Vodka or Schnapps"
        },
        {
            "quantity": "2",
            "measure": "cup",
            "ingredient": "Ice"
        },
        {
            "quantity": "1",
            "measure": "splash",
            "ingredient": "Red wine or Prosecco on top of each cup"
        }
    ],
    "directions": [
        "Add the Frozen & Sliced Peaches with Peach Vodka or Schnapps and Ice to the blender",
        "Blend well until the mix is uniform but creamy in the blender depending on taste and if needed add more ice or peaches to get it consistent or more vodka to make it more liquid",
        "Pour it on your favorite drink glass and add the splash of Red Wine or Prosecco on top of it to give it a lovely and tasty look"
    ],
    "image": "peach-bellini.jpg",
    "source": "https://www.cookswithcocktails.com/peach-bellini-with-red-wine-homemade-raspberry-liqueur/",
    "keywords": [
        "summer drink",
        "wine",
        "vodka",
        "schnapps",
        "sweet",
        "bellini"
    ]
}

=== alfg/opendrinks/src/recipes/golden-glow-water.json
{
    "name": "Golden Glow Water",
    "description": "A drink to refresh you for the rest of the day.",
    "github": "Oishika-Pradhan",
    "ingredients": [
        {
            "quantity": "1",
            "measure": "cup",
            "ingredient": "water"
        },
        {
            "quantity": "1/2",
            "measure": "teaspoon",
            "ingredient": "ground ginger"
        },
        {
            "quantity": "1/2",
            "measure": "teaspoon",
            "ingredient": "ground turmeric"
        },
        {
            "quantity": "1/2",
            "measure": "teaspoon",
            "ingredient": "ground cayenne pepper"
        },
        {
            "quantity": "2",
            "measure": "teaspoon",
            "ingredient": "honey"
        },
        {
            "quantity": "1/2",
            "measure": "teaspoon",
            "ingredient": "molasses"
        },
        {
            "quantity": "1",
            "measure": "piece",
            "ingredient": "lemon: juiced"
        },
        {
            "quantity": "",
            "measure": "",
            "ingredient": "sparkling water or kombucha for topping"
        },
        {
            "quantity": "",
            "measure": "",
            "ingredient": "Optinal: Citrus slice and fresh mint for garnishing"
        }

    ],
    "directions": [
        "Combine water, ginger, turmeric, cayenne, honey, molasses, and lemon juice in a glass jar.",
        "Shake well to combine.",
        "Chill until ready to drink.",
        "Shake before serving.",
        "Add ice to two glasses, pour over the water and top with sparkling water.",
        "Garnish with citrus slices and fresh mint.",
        "Enjoy!"

    ],
    "image": "golden-glow-water.jpg",
    "source": "https://www.halfbakedharvest.com/golden-glow-water/",
    "keywords": [
        "ginger",
        "turmeric",
        "honey",
        "non-alcoholic"
    ]
}

=== alfg/opendrinks/src/recipes/milo-dinosaur.json
{
    "name": "Milo Dinosaur",
    "description": "Drink made of chocolate-malt, popular in Malaysia and Singapore.",
    "github": "pj",
    "ingredients": [
        {
            "quantity": "6",
            "measure": "tbsp",
            "ingredient": "Nestle Milo powder"
        },
        {
            "quantity": "100",
            "measure": "ml",
            "ingredient": "hot water"
        },
        {
            "quantity": "3/4",
            "measure": "tbsp",
            "ingredient": "condensed milk"
        },
        {
            "quantity": "a few",
            "measure": "cubes",
            "ingredient": "ice"
        },
        {
            "quantity": "3",
            "measure": "tbsp",
            "ingredient": "Nestle Milo powder to top it off"
        }
    ],
    "directions": [
        "Stir Milo and condensed milk with hot water in a tall glass until dissolved.",
        "Add ice cubes and stir lightly.",
        "Add ample amount of Milo to provide a crunchy top."
    ],
    "image": "milo-dinosaur.jpg",
    "keywords": [
        "ice",
        "chocolate",
        "non-alcoholic"
    ]
}

=== alfg/opendrinks/src/recipes/carajillo.json
{
    "name": "Carajillo",
    "description": "Carajillo was born during the colonial era, when Cuba was a Spanish province. Spanish soldiers mixed coffee with liquor to take courage during the fighting.",
    "github": "jcespinosa",
    "ingredients": [
        {
            "quantity": "2",
            "measure": "oz",
            "ingredient": "espresso"
        },
        {
            "quantity": "2",
            "measure": "oz",
            "ingredient": "Liquor (Whiskey, Ron, Brandy)"
        }
    ],
    "directions": [
        "Use your favorite mix of coffee roasted beans to brew 2 oz of espresso.",
        "Let the espresso to stand and cold down a little bit.",
        "Get an Old Fashioned glass and put the 2 oz espresso.",
        "Carefully add the 2 oz of your favorite liquor (Whiskey, Ron or Brandy), this step is critical if you want a good looking cocktail. If done correctly you will get the liquor to fall to the bottom of the glass and you will see a beautiful transition between the two drinks.",
        "Tip: Traditionally, carajillo is served warm, but you can also serve it cold, add some ice cubes if you want.",
        "Tip: Use a liquior named \"Licor 43\", a spanish liquior made with a secret recipe of 43 ingredients (species, herbs, fruits), you will get a most refined taste.",
        "Tip: Brew your coffee with some herbs (cinnamon, clove, an√≠s, and more) to improve the taste."
    ],
    "image": "carajillo.jpg",
    "source": "https://gourmetdemexico.com.mx/bebidas/reconocer-carajillo-perfecto/",
    "keywords": [
        "coffee",
        "liqueur",
        "spices",
        "Whiskey"
    ]
}

=== alfg/opendrinks/src/recipes/kiwi-cucumber-cooler.json
{
    "name": "Kiwi Cucumber Cooler",
    "description": "A refreshing summer drink that can be a cocktail, mocktail or a healthy fruit drink.",
    "github": "sinisterblade",
    "ingredients": [
        {
            "quantity": "1",
            "measure": "",
            "ingredient": "cucumber"
        },
        {
            "quantity": "2",
            "measure": "",
            "ingredient": "kiwi fruit"
        },
        {
            "quantity": "50",
            "measure": "",
            "ingredient": "mint leaves"
        },
        {
            "quantity": "3",
            "measure": "tablespoon",
            "ingredient": "sugar"
        },
        {
            "quantity": "1",
            "measure": "",
            "ingredient": "lemon"
        },
        {
            "quantity": "0.5",
            "measure": "teaspoon",
            "ingredient": "chia seeds (optional)"
        },
        {
            "quantity": "1",
            "measure": "can",
            "ingredient": "tonic water"
        },
        {
            "quantity": "30",
            "measure": "ml",
            "ingredient": "gin per drink (optional)"
        }
    ],
    "directions": [
        "Soak the chia seeds in two tablespoons of water.",
        "Peel the cucumber and the kiwi, and cut them into small pieces. Ensure that the cucumber is not overripe and seeds are soft.",
        "Blend the cucumber in a mixer. When the cucumber is well-blended, add kiwi, mint leaves, lemon & sugar.",
        "White sugar can be replaced with 1 tablespoon honey.",
        "Pour the juice in a glass and add soaked chia seeds, ice and top it up with tonic water.",
        "Chop the second kiwi into small pieces and use for garnishing.",
        "For the cocktail, do not add chia seeds and add gin instead."
    ],
    "image": "kiwi-cucumber-cooler.jpg",
    "source": "http://kitchenfables.com/kiwi-cucumber-cooler-cocktail-mocktail",
    "keywords": [
        "fruit",
        "lemon",
        "mint",
        "non-alcoholic",
        "alcoholic"
    ]
}
