=== alfg/opendrinks/scripts/recipe_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/alfg/opendrinks/master/scripts/recipe_schema.json",
    "title": "Recipe",
    "description": "A recipe of a drink or cocktail for opendrinks",
    "type": "object",
    "properties": {
      "name": {
        "description": "The name of the drink",
        "type": "string"
      },
      "description": {
        "description": "A short text describing the drink",
        "type": "string"
      },
      "github": {
        "description": "Github-Username of the contributor",
        "type": "string"
      },
      "ingredients": {
        "description": "The ingredients used for the drink",
        "type": "array",
        "minItems": 1,
        "items": {
          "description": "An ingredient",
          "type" :"object",
          "properties": {
            "quantity": {
              "description": "How much of the ingredient is needed",
              "type": "string"
            },
            "measure": {
              "description": "The unit of measurement of what is needed",
              "type": "string"
            },
            "ingredient": {
              "description": "The name of the ingredient",
              "type": "string"
            }
          },
          "required": [
            "quantity",
            "ingredient"
          ] 
        }
      },
      "directions": {
        "description": "How the drink is made",
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "string"
        }
      },
      "image": {
        "description": "An image of the drink",
        "type": "string"
      },
      "source": {
        "description": "Source of the recipe",
        "type": "string"
      },
      "keywords": {
        "description": "Keywords that describe the drink",
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "string"
        }
      }
    },
    "required": [
      "name",
      "description",
      "ingredients",
      "directions",
      "image",
      "keywords"
    ]
  }

=== alfg/opendrinks/src/recipes/dagobah-slug-slinger.json
{
    "name": "Dagobah Slug Slinger",
    "description": "It's uh... it's green.",
    "github": "bibliofilo",
    "ingredients": [
        {
            "quantity": "15",
            "measure": "ml",
            "ingredient": "Ginger Syrup"
        },
        {
            "quantity": "2",
            "measure": "dashes",
            "ingredient": "grapefruit bitters"
        },
        {
            "quantity": "30",
            "measure": "ml",
            "ingredient": "orange-tangerine juice"
        },
        {
            "quantity": "22",
            "measure": "ml",
            "ingredient": "Blue Curaçao"
        },
        {
            "quantity": "60",
            "measure": "ml",
            "ingredient": "Reposado Tequila"
        }
    ],
    "directions": [
        "Shake & Strain",
        "Garnish with Rosemary"
    ],
    "image": "dagobah_slug_linger.jpg",
    "source": "https://youtu.be/VKboM2sts9U",
    "keywords": [
        "alcoholic",
        "ginger",
        "grapefruit",
        "orange juice",
        "tangerine juice",
        "blue curaçao",
        "tequila",
        "margarita",
        "star wars"
    ]
}

=== alfg/opendrinks/src/recipes/taro-fresh-milk.json
{
    "name": "Taro Fresh Milk",
    "description": "Taro fresh milk is a drink that you find a lot in cafes in Indonesia, young people love it.",
    "github": "muhamadiqbalriv",
    "ingredients": [
        {
            "quantity": "2",
            "measure": "",
            "ingredient": "Tablespoons of taro powder"
        },
        {
            "quantity": "1",
            "measure": "",
            "ingredient": "Glass of pure cow's milk"
        },
        {
            "quantity": "1/2",
            "measure": "",
            "ingredient": "Tablespoons of liquid sugar"
        },
        {
            "quantity": "Needed",
            "measure": "",
            "ingredient": "Ice cubes"
        }
    ],
    "directions": [
        "Dissolve taro powder with liquid sugar, add a little warm water then mix well.",
        "Prepare whole milk in a serving glass, put ice cubes, then pour the liquid sugar that has been mixed with taro powder. Serve."
    ],
    "image": "taro-fresh-milk.jpg",
    "keywords": [
        "taro",
        "milk",
        "fresh",
        "vegan"
	]
}

=== alfg/opendrinks/src/recipes/pedo-de-gorila.json
{
    "name": "Pedo de Gorila",
    "description": "Esta es una bebida bastante fuerte, la idea principal es servir un vaso de cerveza clara a la mitad, luego en un shot de teuquila calentado a la mayor temperatura posible y despues se echa en el vaso de cerveza y cuando el shot hace contacto con la cerveza hay que beberlo ràpidamente ya que el liquido generara una reacción bastante brusca.",
    "github": "rolandoivan23",
    "ingredients": [
        {
            "quantity": "1/2",
            "measure": "Lt",
            "ingredient": "Cerveza clara"
        },
        {
            "quantity": "1",
            "measure": "Shot",
            "ingredient": "de vidrio resistenete a altas temperaturas"
        },
        {
            "quantity": "50-70",
            "measure": " mls",
            "ingredient": "de tequila reposado"
        }
    ],
    "directions": [
        "Servir un vaso a la mitad de cerveza clara",
        "Llenar un shot de tequila",
        "Calentar el shot de tequila a la mayor temperatura posible",
        "Echar el shot de tequila al vaso de cerveza",
        "Tomar rápidamente todo el liquido subiendo a presión",
        "Rezar a Dios que no te de una congestion alcohólica"
    ],
    "image": "pedo-de-gorila.jpg",
    "keywords": [
        "alcoholic", 
        "beer",
        "tequila"
    ]
}

=== alfg/opendrinks/src/recipes/rose-sangria.json
{
    "name": "Rose Sangria",
    "description": "A simple and tasty rosé sangria.",
    "github": "MrValraven",
    "ingredients": [
        {
            "quantity": "2",
            "measure": "",
            "ingredient": "oranges"
        },
        {
            "quantity": "10",
            "measure": "",
            "ingredient": "strawberries"
        },
        {
            "quantity": "3",
            "measure": "teaspoon",
            "ingredient": "brown sugar"
        },
        {
            "quantity": "11",
            "measure": "oz (or 330ml)",
            "ingredient": "7up or any citrus soda"
        },
        {
            "quantity": "17",
            "measure": "oz (or 550Mml)",
            "ingredient": "rosé wine"
        }
    ],
    "directions": [
        "Slice the oranges and strawberries into a jar.",
        "Place the sugar and muddle all the ingredients.",
        "Fill the jar with ice.",
        "Place the soda and the wine inside the jar.",
        "Mix it all up, in circular motions, going in a upwards motion.",
        "Add some mint leaves as garnish and enjoy!"

    ],
    "image": "rose-sangria.jpg",
    "keywords": [
        "summer",
        "fresh",
        "sangria",
        "sweet",
        "vegan",
        "alcoholic"
    ]
}

=== alfg/opendrinks/src/recipes/elderflower-tini.json
{
    "name": "Elderflower-tini",
    "description": "A sweet twist to your average martini.",
    "github": "lalawuhan",
    "ingredients": [
        {
            "quantity": "50",
            "measure": "ml",
            "ingredient": "Vodka"
        },
        {
            "quantity": "15",
            "measure": "ml",
            "ingredient": "Lemon Juice"
        },
        {
            "quantity": "25",
            "measure": "ml",
            "ingredient": "Elderflower syrup"
        }
    ],
    "directions": [
        "Chill serving glass in freezer.",
        "Pour ingredients into mixing glass with ice in order listed and shake.",
        "Strain into chilled serving glass."
    ],
    "image": "elderflower-tini.jpg",
    "keywords": [
        "elderflower",
        "alcoholic",
        "vegan"
    ]
}

=== alfg/opendrinks/src/recipes/chai-e-zanjafeel.json
{
    "name": "Chai E Zanjafeel",
    "description": "Afghan ginger tea that is refreshing on hot days or when you feel sick.",
    "github": "FarbrorGarbo",
    "ingredients": [
        {
            "quantity": "3",
            "measure": "tsp",
            "ingredient": "Green tea"
        },
        {
            "quantity": "2",
            "measure": "tsp",
            "ingredient": "Sugar"
        },
        {
            "quantity": "2-3",
            "measure": "tsp",
            "ingredient": "Ground ginger"
        },
        {
            "quantity": "1",
            "measure": "tbs",
            "ingredient": "Walnuts, very finely chopped or ground"
        },
        {
            "quantity": "3 ½",
            "measure": "cups",
            "ingredient": "Water"
        }
    ],
    "directions": [
        "Bring 3½ cups water to a boil in a pan, then add the tea and sugar. Continue boiling for about 2 minutes, then strain.",
        "Pour the tea back into the pan and add the ground ginger and walnuts.",
        "Boil again for about 2 minutes."
    ],
    "image": "chai-e-zanjafeel.jpg",
    "source": "http://www.afghankitchenrecipes.com/recipe/chai-e-zanjafeel-ginger-tea/",
    "keywords": [
        "afghan",
        "ginger",
        "tea",
        "refreshing",
        "non-alcoholic"
    ]
}

=== alfg/opendrinks/src/recipes/coconut-coffee.json
{
    "name": "Coconut Coffee",
    "description": "A new Hanoian specialty, where the creaminess of coconut mix perfectly well with the bitter taste of espresso",
    "github": "antran22",
    "ingredients": [
        {
            "quantity": "1",
            "measure": "shot",
            "ingredient": "Espresso"
        },
        {
            "quantity": "50",
            "measure": "ml",
            "ingredient": "Coconut Milk"
        },
        {
            "quantity": "20",
            "measure": "ml",
            "ingredient": "Condensed Milk"
        },
        {
            "quantity": "20",
            "measure": "ml",
            "ingredient": "Whipping Cream"
        },
        {
            "quantity": "20",
            "measure": "gram",
            "ingredient": "Ice"
        },
        {
            "quantity": "1",
            "measure": "scoop",
            "ingredient": "Coconut Ice Cream (optional)"
        },
        {
            "quantity": "10",
            "measure": "gram",
            "ingredient": "Coconut Flesh (optional)"
        }
    ],
    "directions": [
        "Prepare one shot of espresso. If you can't get espresso, drip brewed coffee works fine but the taste won't be as robust.",
        "Mix the coconut milk, condensed milk, whipping cream, ice together in a blender.",
        "Put the coconut mixture into a glass cup, pour the espresso over.",
        "Garnish with the ice cream scoop or the coconut flesh.",
        "This drink tastes best on a hot day."
    ],
    "image": "coconut-coffee.jpg",
    "keywords": [
        "coffee",
        "coconut",
        "cream",
        "cold",
        "non-alcoholic",
        "organic"
    ]
}

=== alfg/opendrinks/src/recipes/moscow-mule-simple.json
{
  "name": "Simple Moscow Mule",
  "description": "A simple, sweet and sour cocktail. And an excuse to buy a Moscow Mule Mug.",
  "github": "coma-toast",
  "ingredients": [
    {
      "quantity": "60-100",
      "measure": "ml",
      "ingredient": "Vodka"
    },
    {
      "quantity": "20",
      "measure": "ml",
      "ingredient": "Lime juice"
    },
    {
      "quantity": "40",
      "measure": "ml",
      "ingredient": "Lemon juice"
    },
    {
      "quantity": "6",
      "measure": "oz",
      "ingredient": "Ginger Ale - fill to taste"
    }
  ],
  "directions": [
    "Start with several ice cubes in a Moscow Mule mug.",
    "Add lime and lemon juice.",
    "Add Vodka.",
    "Fill with Ginger Ale.",
    "Serve with a fresh mint leaf."
  ],
  "image": "moscow-mule.jpg",
  "keywords": [
    "vodka",
    "ginger ale",
    "citrus",
    "mint",
    "alcoholic",
    "simple",
    "vegan"
  ]
}
