=== alfg/opendrinks/scripts/recipe_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/alfg/opendrinks/master/scripts/recipe_schema.json",
    "title": "Recipe",
    "description": "A recipe of a drink or cocktail for opendrinks",
    "type": "object",
    "properties": {
      "name": {
        "description": "The name of the drink",
        "type": "string"
      },
      "description": {
        "description": "A short text describing the drink",
        "type": "string"
      },
      "github": {
        "description": "Github-Username of the contributor",
        "type": "string"
      },
      "ingredients": {
        "description": "The ingredients used for the drink",
        "type": "array",
        "minItems": 1,
        "items": {
          "description": "An ingredient",
          "type" :"object",
          "properties": {
            "quantity": {
              "description": "How much of the ingredient is needed",
              "type": "string"
            },
            "measure": {
              "description": "The unit of measurement of what is needed",
              "type": "string"
            },
            "ingredient": {
              "description": "The name of the ingredient",
              "type": "string"
            }
          },
          "required": [
            "quantity",
            "ingredient"
          ] 
        }
      },
      "directions": {
        "description": "How the drink is made",
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "string"
        }
      },
      "image": {
        "description": "An image of the drink",
        "type": "string"
      },
      "source": {
        "description": "Source of the recipe",
        "type": "string"
      },
      "keywords": {
        "description": "Keywords that describe the drink",
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "string"
        }
      }
    },
    "required": [
      "name",
      "description",
      "ingredients",
      "directions",
      "image",
      "keywords"
    ]
  }

=== alfg/opendrinks/src/recipes/negrumi.json
{
    "name": "Negrumi",
    "description": "A variant of the best known Negroni with addition of pink grapefruit. The name is a portmanteau that blends the two words \"Negroni\" and \"Agrumi\" (italian for \"Citrus fruits\") together.",
    "github": "AlbyIanna",
    "ingredients": [
        {
            "quantity": "1",
            "measure": "oz",
            "ingredient": "Gin"
        },
        {
            "quantity": "1",
            "measure": "oz",
            "ingredient": "Campari"
        },
        {
            "quantity": "1",
            "measure": "oz",
            "ingredient": "Pink grapefruit juice"
        },
        {
            "quantity": "1",
            "measure": "slice",
            "ingredient": "pink grapefruit"
        }
    ],
    "directions": [
        "Combine the spirits into a mixing glass with ice.",
        "Stir until chilled.",
        "Strain into a rocks glass filled with large ice cubes.",
        "Garnish with a slice of pink grapefruit."
    ],
    "image": "negrumi.jpg",
    "keywords": [
        "gin",
        "alcoholic",
        "summer",
        "vegan",
        "simple",
        "grapefruit",
        "pink",
        "negroni"
    ]
}

=== alfg/opendrinks/src/recipes/jungle-bird.json
{
    "name": "Jungle Bird",
    "description": "This classic Tiki drink was created in 1978 at the Aviary bar of the Kuala Lumpur Hilton.",
    "github": "caseydierking",
    "ingredients": [
        {
            "quantity": "1 1/2",
            "measure": "oz",
            "ingredient": "dark rum"
        },
        {
            "quantity": "3/4",
            "measure": "oz",
            "ingredient": "Campari"
        },
        {
            "quantity": "1/2",
            "measure": "oz",
            "ingredient": "Simple Syrup"
        },
        {
            "quantity": "1 1/2",
            "measure": "oz",
            "ingredient": "Fresh Pineapple Juice"
        },
        {
            "quantity": "1/2",
            "measure": "oz",
            "ingredient": "fresh lime juice"
        }
    ],
    "directions": [
        "Fill a mixing glass three-quarters with ice, and add all of the ingredients.",
        "Shake until chilled for about 30 seconds.",
        "Strain into a rocks glass over ice cubes or one large piece of ice, and add the garnish."
    ],
    "image": "jungle-bird.jpg",
    "source": "https://www.liquor.com/recipes/jungle-bird/#gs.7cblkv" ,
    "keywords": [
        "alcoholic",
        "fresh",
        "vegan",
        "fruit"
    ]
}

=== alfg/opendrinks/src/recipes/mexican-sonora-michelada.json
{
	"name": "Mexican Michelada Sinaloa Style",
	"description": "Is a Mexican cocktail with beer and seafood, prepared with lemon, shrimp, tomato juice, clam, inglesa sauce, and celery add a delicious flavor to the drink.",
	"github": "evertcode",
	"ingredients": [{
			"quantity": "1",
			"measure": "",
			"ingredient": "Dark Beer"
		},
		{
			"quantity": "1",
			"measure": "Teaspoon",
			"ingredient": "inglesa sauce"
		},
		{
			"quantity": "1/2",
			"measure": "Teaspoon",
			"ingredient": "hot sauce"
		},
		{
			"quantity": "1/2",
			"measure": "Cups",
			"ingredient": "tomato juice with clams"
		},
		{
			"quantity": "1",
			"measure": "",
			"ingredient": "Lemon"
		},
		{
			"quantity": "50",
			"measure": "Grams",
			"ingredient": "'pacotilla' shrimp"
		},
		{
			"quantity": "2",
			"measure": "Sticks",
			"ingredient": "celery, cut into strips and without skin"
		},
		{
			"quantity": "",
			"measure": "",
			"ingredient": "Salt to taste"
		},
		{
			"quantity": "",
			"measure": "",
			"ingredient": "Black pepper, to taste"
		},
		{
			"quantity": "",
			"measure": "",
			"ingredient": "Chili pepper, to taste"
		}
	],
	"directions": [
		"With the help of a wet napkin and a flat plate covered with chili pepper, frost the ball glass.",
		"Add all the ingredients (except the beer and the celery).",
		"Add the Beer.",
		"Add the celery sticks.",
		"Mix the drink slightly with a spoon.",
		"Enjoy!"
	],
	"image": "mexican-sinaloa-michelada.jpg",
	"keywords": [
		"lemon",
		"salt",
		"beer",
		"shrimp",
		"clams",
		"tomato",
		"alcoholic",
		"mexican",
		"cold"
	]
}

=== alfg/opendrinks/src/recipes/peppermint-shake.json
{
    "name": "Peppermint Shake",
    "description": "Peppermint Milkshakes - simple, quick and delicious! They're one of our favorite holiday treats! A cool drink made from vanilla ice cream, milk, peppermint extract and topped with whipped cream and crushed candy cane pieces!",
    "github": "iampk94",
    "ingredients": [
        {
            "quantity": "2",
            "measure": "cups",
            "ingredient": "Vanilla ice cream"
        },
        {
            "quantity": "1/2",
            "measure": "cup",
            "ingredient": "Milk"
        },
        {
            "quantity": "1/4",
            "measure": "cup",
            "ingredient": "Candy cane crushed"
        },
        {
            "quantity": "1",
            "measure": "tsp",
            "ingredient": "Peppermint extract"
        },
        {
            "quantity": "",
            "measure": "",
            "ingredient": "Whipped cream"
        }
    ],
    "directions": [
        "Add ice cream, milk, crushed cane pieces and peppermint extract to a blender.",
        "Mix until well combined.",
        "Pour into glass and top with whipped cream and candy cane pieces."
    ],
    "image": "peppermint-milkshake.jpg",
    "keywords": [
        "ice cream",
        "milkshake",
        "non-alcoholic",
        "vegan"
    ]
}

=== alfg/opendrinks/src/recipes/targoviste-twist.json
{
    "name": "Targoviste Twist",
    "description": "A spicy and tangy drink that pays tribute to the history and culture of Targoviste, Romania",
    "github": "eduardconstantin",
    "ingredients": [
        {
            "quantity": "2",
            "measure": "oz",
            "ingredient": "rum"
        },
        {
            "quantity": "1/2",
            "measure": "oz",
            "ingredient": "lime juice"
        },
        {
            "quantity": "1/4",
            "measure": "oz",
            "ingredient": "simple syrup"
        },
        {
            "quantity": "2",
            "measure": "dashes",
            "ingredient": "Tabasco sauce"
        },
        {
            "quantity": "",
            "measure": "",
            "ingredient": "soda water"
        }
    ],
    "directions": [
        "Fill a cocktail shaker with ice.",
        "Add the rum, lime juice, simple syrup, and Tabasco sauce and shake well.",
        "Strain into a highball glass filled with ice.",
        "Top with soda water and garnish with a lime wedge."
    ],
    "image": "targoviste-twist.jpg",
    "keywords": [
        "cocktail",
        "rum",
        "lime juice",
        "Tabasco sauce"
    ]
}

=== alfg/opendrinks/src/recipes/spritz.json
{
    "name": "Spritz",
    "description": "Tipical drink from Veneto region (Italy), invented between the end of the 1700s and the beginning of the 1800s.",
    "github": "GiovanniCS",
    "ingredients": [
        {
            "quantity": "1/3",
            "measure": "",
            "ingredient": "Aperol"
        },
        {
            "quantity": "1/3",
            "measure": "",
            "ingredient": "Seltz "
        },
        {
            "quantity": "1/3",
            "measure": "",
            "ingredient": "White wine"
        },
        {
            "quantity": "6",
            "measure": "cubes",
            "ingredient": "Ice"
        },
        {
            "quantity": "1",
            "measure": "slice",
            "ingredient": "Orange"
        }
    ],
    "directions": [
        "Cut the orange in slices.",
        "Add the ice cubes in the glass.",
        "Add 1/3 of Aperol and 1/3 of white wine.",
        "Finally sprinkle the soda in the glass.",
        "Garnish with one slice of orange and serve.",
        "Enjoy!"
    ],
    "image": "spritz.jpg",
    "keywords": [
        "spritz",
        "wine",
        "orange",
        "aperol",
        "selz"
    ]
}

=== alfg/opendrinks/src/recipes/irish-breakfast-shot.json
{
    "name": "Irish Breakfast Shot",
    "description": "Orange Juice and Jameson in a shot.",
    "github": "cbowersock",
    "ingredients": [
        {
            "quantity": "2oz",
            "measure": "shot glass",
            "ingredient": "Jameson Irish Whiskey"
        },
        {
            "quantity": "1oz",
            "measure": "shot glass",
            "ingredient": "Orange Juice"
        }
    ],
    "directions": [
        "Pour 2oz of Jameson into a small highball glass.",
        "Add 1oz of orange juice and stir.",
        "You're done!"
    ],
    "image": "irish-breakfast-shot.jpg",
    "keywords": [
        "jameson",
        "orange",
        "juice",
        "shot"
    ]
}

=== alfg/opendrinks/src/recipes/kopi.json
{
	"name": "Kopi",
	"description": "Kopi is a type of traditional coffee local to Singapore and Malaysia. It is a highly caffeinated black coffee served with milk and sugar. ",
	"github": "ChenQirui1",
	"ingredients": [{
			"quantity": "1",
			"measure": "4/5 cup (‘cup’ refers to your cup, not US measuring cup)",
			"ingredient": "Kopi concentrate"
		},
		{
			"quantity": "1",
			"measure": "1 teaspoon",
			"ingredient": "Condensed milk"
		},
		{
			"quantity": "1",
			"measure": "20g / ~3 teaspoons",
			"ingredient": "Evaporated milk"
		}
	],

	"directions": [
		"To an empty cup, add condensed milk and evaporated milk (feel free to tweak amount to taste)",
		"Add 4/5 cup of kopi concentrate",
		"Top up with hot water (95 to 98°C). Feel free to dilute your kopi to desired strength.",
		"Stir well to dissolve milk."
	],
	"image": "kopi.jpg",
	"source": "https://www.alliancecoffee.net/kopi-recipes/#kopi",
	"keywords": [
		"coffee",
		"singaporean",
		"malaysian"
	]
}
